disabled_rules:
  - trailing_comma

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - discouraged_optional_collection
  - empty_xctest_method
  - fatal_error_message
  - implicit_return
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - number_separator
  - redundant_type_annotation
  - sorted_imports
  - switch_case_on_newline
  - trailing_closure
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - xct_specific_matcher

identifier_name:
  min_length: 1
  excluded:
    - __allTests
    - __allTests()

type_name:
  min_length: 1
